### ISSUE TITLE
How to add instances?

### ISSUE THREAD

**Issue by code-IM-perfect** [bssec/MEGA-Instances#14]
I already have 2 instances set up but now I want to add another, is there a way this can be done without resetting everything?

**Comment by schrmh** [comment]
@code-IM-perfect 
https://github.com/NicoVarg99/MEGA-Instances/blob/ef8b9e14dc19855a76d3ef3af5907f8567bce1c3/mega_instances.sh#L56-L60
You might only need to create subfolders.
Most likely like this:
```
cd $HOME/MEGA
mkdir new_instance_name
```

**Comment by manuelsongokuh** [comment]
this topic will be close because your reply is correct: https://github.com/NicoVarg99/MEGA-Instances/issues/14#issuecomment-1435966042
