### ISSUE TITLE
usage of mkdir

### ISSUE THREAD

**Issue by PhilippVerpoort** [bssec/MEGA-Instances#2]
You may want to use mkdir -p or pipe the output of mkdir into /dev/null. Otherwise users may receive additional error messages. Avoiding error messages will give users of your script one less thing to worry about. For example:

`mkdir /home/$USER/.config/autostart`

is very likely to give you an error like

`mkdir: cannot create directory`

since the autostart directory is already existent on most machines.

**Comment by NicoVarg99** [comment]
Done. Thank you again.
